### PR TITLE
:art: Replacing SuperTabs by SwiperJS

### PR DESCRIPTION
**Pull request by RaphaelFelten**
Hey, here I am again with a new pull request. This time it's a little more than last time :)
I've noticed that swiping between tabs/segments did not change the active segment in the top. I've had the same problem in one of the apps I've developed.

I actually found that using [SwiperJS](https://swiperjs.com/angular) works like a charm. Just a couple of configurations are necessary for it to work correctly.

For example, I've had to import and add some CSS in the global.scss file. That way you don't have to copy the CSS from component to component.

Let me know what you think ;)

P.S.: When pulling the project, I wasn't able to start the dev environment. For some reason, the package ionic-native/core was missing in the package.json, but was needed by some other package. That's why you'll see that in the package.json.
I've also kept the imports and stuff from SuperTabs in case you didn't like this or wanted to test something. I'll remove everything if you accept the changes :)

Raphael

### CODE REVIEW

**Comment by Fllorent0D** [comment]
Wow amazing 👀 
That's actually a change I wanted to do at some point! Thanks a lot for this.
At first glance, it seems fine for me.
I will checkout and take a deep look tomorrow 😉

**Comment by Fllorent0D** [comment]
Sorry for the delay.

I detected a small problem with the tab bar when a back navigation occurs. Seems like the scrollbar is bugged. 
https://user-images.githubusercontent.com/13313104/171993531-75e3aede-e5ab-4dc8-a8da-9669238cf7a9.mov

I see one thing that would need some adaptation to avoid code duplication between the three pages where there are tabs. The class `AbstractPageTabsComponent` is designed to hold the swiper configurations and implementation.

**Comment by Fllorent0D** [comment]
I regrouper the configuration but the issue with the scrollbar is still there 😕

**Comment by RaphaelFelten** [comment]
Hm maybe the swiper needs to be updated on page enter. Since you're navigating back, ngAfterViewInit is not fired again.
I'll try something and let you know if that works :)

**Comment by RaphaelFelten** [comment]
I've simply added that the active tab is selected when the view re-enters. This seems to resolve the issue, you can try it on your end and see if that works :)

**Comment by Fllorent0D** [comment]
I still have an issue with the back navigation. The tab bar item are not working when re-entering a view. 

Uploading Enregistrement de l’écran 2022-06-11 à 22.55.36.mov…

**Comment by RaphaelFelten** [comment]
Oh ok I see. So swiping still works but clicking does not work anymore? That's strange indeed. Not sure how this can be fixed. Sorry I thought it only affected the active tab..

**Comment by Fllorent0D** [comment]
I've worked a bit on this topic. What I did:
- I removed the scrollbar module which seems broken with Ionic navigation. 
- Removed the AbstractPageTabs which was breaking ng14 lazy modules. Will find a solution to centralize all swiper config.
- I put back native ion-segment to match native design
https://user-images.githubusercontent.com/13313104/174953098-f2004d90-849d-4044-82c8-1ebbaf011a60.mov
https://user-images.githubusercontent.com/13313104/174953101-59a9a65e-4c7f-4211-aa60-627c3457a7c5.mov

**Pull request merged**
